include:
  - project: 'tcw-group/technology/platform-engineering/development-operations/cicd-configurations'
    ref: 'main'
    file: '/go/pipelines/x1/go.webservice.cloud.default.pipeline.yml'

variables:
  PROJECT_NAME: 'security-rules'
  DEPLOYMENT_NAME: 'security-rules'
  OPEN_API_DOCUMENTATION: ''

  ## AKS Tags ####################################################################################
  APPLICATION_OWNER: 'data-management'
  APPLICATION_TYPE: 'webservice'
  APPLICATION_SENSITIVITY: 'public'
  ################################################################################################
  
  ## DOCKER CONFIGURATIONS ########################################################################
  CUSTOM_DOCKERFILE: 'false'
  #################################################################################################

  ## DNS Configurations ###########################################################################
  ENABLE_TLS: 'false'
  DOMAIN: data-quality 
  #################################################################################################

  ## Workload Identity Configurations #############################################################
  ENABLE_WORKLOAD_IDENTITY: 'true'
  NONPROD_AZURE_CLIENT_ID: 'b14585d8-d095-4815-b320-d625f98ae9f7'
  NONPROD_K8S_SERVICE_ACCT: 'sa-np-desecurityrules'
  PROD_AZURE_CLIENT_ID: 'f7b6ad6f-a0a9-4512-bd07-2b10b9bd3c15'
  PROD_K8S_SERVICE_ACCT: 'sa-pd-desecurityrules'
  #################################################################################################

  ## Authorization Configurations #################################################################
  ENABLE_AUTHORIZATIONS: 'false'
  PDPKEY_DEVELOPMENT:
  PDPKEY_QA:
  PDPKEY_PRODUCTION:
  #################################################################################################