CREATE TABLE IF NOT EXISTS public."RULE_TYPE" (
    "RULE_TYPE_ID"  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME"          text,
    "DESCRIPTION"   text,
    "RULE_GROUP_ID" bigint,
    "CREATED_DATE"  timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "CREATED_BY"    text
);
