
CREATE OR REPLACE TABLE EXCEPTION_STATUS_2
(
EXCEPTION_STATUS_ID INT
, NAME VARCHAR(100)
, SORT_ORDER INT
, CREATED_BY VARCHAR(100)
, CREATED_DATE TIMESTAMP_NTZ(9)
)
go
INSERT INTO EXCEPTION_STATUS_2(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
SELECT EXCEPTION_STATUS_ID , CODE, SORT_ORDER,MODIFIED_BY, MODIFIED_DATE
FROM EXCEPTION_STATUS
go

