CREATE OR REPLACE PROCEDURE GET_SEVERITY_TYPE()
RETURNS TABLE ("CODE" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "CODE"
        FROM "CATEGORY_TYPE"
        ORDER BY "CATEGORY_RANK" ASC, "CODE" ASC
    );
    RETURN TABLE(res);
END;
$$;
