CREATE OR REPLACE PROCEDURE GET_EXCEPTIONS("ASSET_ID" VARCHAR)
RETURNS TABLE(
    "SECURITY_EXCEPTION_ID" NUMBER(38,0),
    "RULE_ID" NUMBER(38,0),
    "ALADDIN_ID" VARCHAR,
    "RUN_DATE" TIMESTAMP,
    "RUN_START" TIMESTAMP,
    "RESULT_TYPE_ID" NUMBER(38,0),
    "EXCEPTION_SOURCE_ID" NUMBER(38,0),
    "EXCEPTION_STATUS_ID" NUMBER(38,0),
    "SEVERITY_TYPE_ID" NUMBER(38,0),
    "PROCESS_TYPE_ID" NUMBER(38,0),
    "CATEGORY_TYPE_ID" NUMBER(38,0),
    "ASSIGN_TO" VARCHAR,
    "ASSIGNED_BY" VARCHAR,
    "ISSUE_DESCRIPTION" VARCHAR,
    "CREATED_DATE" TIMESTAMP,
    "CREATED_BY" VARCHAR,
    "MODIFIED_DATE" TIMESTAMP,
    "MODIFIED_BY" VARCHAR
)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT SECURITY_EXCEPTION_ID, RULE_ID, ALADDIN_ID, RUN_DATE, RUN_START,
               RESULT_TYPE_ID, EXCEPTION_SOURCE_ID, EXCEPTION_STATUS_ID, SEVERITY_TYPE_ID,
               PROCESS_TYPE_ID, CATEGORY_TYPE_ID, ASSIGN_TO, ASSIGNED_BY,
               ISSUE_DESCRIPTION, CREATED_DATE, CREATED_BY,
               MODIFIED_DATE, MODIFIED_BY
        FROM SECURITY_EXCEPTION
        WHERE ALADDIN_ID = :ASSET_ID
    );
    RETURN TABLE(res);
END;
$$;
