CREATE OR REPLACE PROCEDURE GET_EXCEPTION_STATUS()
RETURNS TABLE("CODE" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "CODE"
        FROM "EXCEPTION_STATUS"
        ORDER BY "SORT_ORDER" ASC, "CODE" ASC
    );
    RETURN TABLE(res);
END;
$$;
