CREATE OR REPLACE PROCEDURE GET_RULE_TYPES(
    P_RULE_GROUP VARCHAR
)
RETURNS TABLE("RULE_TYPE_NAME" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT rt."NAME" AS "RULE_TYPE_NAME"
        FROM "RULE_TYPE" rt
        JOIN "RULE_GROUP" rg
          ON rg."RULE_GROUP_ID" = rt."RULE_GROUP_ID"
        WHERE rg."NAME" = :P_RULE_GROUP
        ORDER BY rt."RULE_TYPE_ID" ASC
    );
    RETURN TABLE(res);
END;
$$;
