DROP FUNCTION IF EXISTS public."GET_EXCEPTION_STATUS"();

CREATE OR REPLACE FUNCTION public."GET_EXCEPTION_STATUS"()
RETURNS TABLE("CODE" text)
LANGUAGE sql
AS $$
    SELECT "CODE"
    FROM public."EXCEPTION_STATUS"
    ORDER BY "SORT_ORDER" ASC, "CODE" ASC;
$$;
