DROP FUNCTION IF EXISTS public."GET_EXCEPTION_TYPE"();

CREATE OR REPLACE FUNCTION public."GET_EXCEPTION_TYPE"()
RETURNS TABLE("CODE" text)
LANGUAGE sql
AS $$
    SELECT "CODE"
    FROM public."EXCEPTION_TYPE"
    ORDER BY "EXCEPTIONTYPERANK" ASC;
$$;
