DROP FUNCTION IF EXISTS public."GET_PRIORITY_TYPE"();

CREATE OR REPLACE FUNCTION public."GET_PRIORITY_TYPE"()
RETURNS TABLE("CODE" text)
LANGUAGE sql
AS $$
    SELECT "CODE"
    FROM public."SEVERITY_TYPE"
    ORDER BY "SEVERITY_RANK" ASC, "CODE" ASC;
$$;
