CREATE OR REPLACE PROCEDURE GET_RULES(
    P_PROCESS_TYPE VARCHAR,
    P_RULE_TYPE    VARCHAR DEFAULT NULL
)
RETURNS TABLE(
    "RULE_ID"      NUMBER,
    "RULE_NAME"    VARCHAR,
    "RULE_COMMAND" VARCHAR,
    "ENVIRONMENT"  VARCHAR
)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT r."RULE_ID",
               r."RULE_NAME",
               r."RULE_COMMAND",
               r."ENVIRONMENT"
        FROM "RULE" r
        JOIN "RULE_TYPE" rt ON rt."RULE_TYPE_ID" = r."RULE_TYPE_ID"
        WHERE (:P_RULE_TYPE IS NULL OR :P_RULE_TYPE = 'All' OR rt."NAME" = :P_RULE_TYPE)
    );
    RETURN TABLE(res);
END;
$$;
