CREATE OR REPLACE PROCEDURE GET_PRIORITY_TYPE()
RETURNS TABLE("CODE" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "CODE"
        FROM "SEVERITY_TYPE"
        ORDER BY "SEVERITY_RANK" ASC, "CODE" ASC
    );
    RETURN TABLE(res);
END;
$$;
