CREATE OR REPLACE PROCEDURE GET_EXCEPTION_TYPE()
RETURNS TABLE("CODE" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "CODE"
        FROM "EXCEPTION_TYPE"
        ORDER BY "EXCEPTIONTYPERANK" ASC
    );
    RETURN TABLE(res);
END;
$$;
