DROP FUNCTION IF EXISTS public."GET_SEVERITY_TYPE"();

CREATE OR REPLACE FUNCTION public."GET_SEVERITY_TYPE"()
RETURNS TABLE("CODE" text)
LANGUAGE sql
AS $$
    SELECT "CODE"
    FROM public."CATEGORY_TYPE"
    ORDER BY "CATEGORY_RANK" ASC, "CODE" ASC;
$$;
