CREATE OR REPLACE PROCEDURE "GET_EXCEPTIONS"("ASSET_ID" VARCHAR)
RETURNS TABLE ("SECURITY_EXCEPTION_ID" NUMBER(38,0), "RULE_NAME" VARCHAR, "ALADDIN_ID" VARCHAR, "RUN_DATE" TIMESTAMP_NTZ(9), "RUN_START" TIMESTAMP_NTZ(9), "RESULT_TYPE_ID" NUMBER(38,0), "EXCEPTION_SOURCE_ID" NUMBER(38,0), "EXCEPTION_STATUS_ID" NUMBER(38,0), "SEVERITY_TYPE_ID" NUMBER(38,0), "PROCESS_TYPE_ID" NUMBER(38,0), "CATEGORY_TYPE_ID" NUMBER(38,0), "ASSIGN_TO" VARCHAR, "ASSIGNED_BY" VARCHAR, "ISSUE_DESCRIPTION" VARCHAR, "CREATED_DATE" TIMESTAMP_NTZ(9), "CREATED_BY" VARCHAR, "MODIFIED_DATE" TIMESTAMP_NTZ(9), "MODIFIED_BY" VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS 
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT SECURITY_EXCEPTION_ID, RULE_NAME, ASSET_ID AS  ALADDIN_ID, RUN_DATE, RUN_START,
               RESULT_TYPE_ID, EXCEPTION_SOURCE_ID, EXCEPTION_STATUS_ID, SEVERITY_TYPE_ID,
               PROCESS_TYPE_ID, CATEGORY_TYPE_ID, ASSIGN_TO, ASSIGNED_BY,
               ISSUE_DESCRIPTION, s.CREATED_DATE, s.CREATED_BY,
               MODIFIED_DATE, MODIFIED_BY
        FROM SECURITY_EXCEPTION s
        JOIN RULE r on s.RULE_ID = r.RULE_ID
        WHERE ALADDIN_ID =  :ASSET_ID
    );
    RETURN TABLE(res);
END;
;
/*
SELECT * FROM SECURITY_EXCEPTION

update SECURITY_EXCEPTION 
SET RULE_ID = 2
WHERE ASSET_ID in ( '82966BAA3', '36274AAD2', 'Z97FR1BS9')

CALL GET_EXCEPTIONS('38384LJ83')
*/