DROP TABLE IF EXISTS public."RULE" CASCADE;

CREATE TABLE public."RULE" (
    "RULE_ID"                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RULE_TYPE_ID"            numeric,
    "RULE_NAME"               varchar(100),
    "RULE_DESCRIPTION"        varchar(512),
    "RULE_COMMAND"            varchar(1024),
    "RESULT_DATE_TYPE"        varchar(100),
    "RULE_RESOLUTION"         varchar(512),
    "BUSINESS_TERM_SOURCE_ID" text,
    "IS_ACTIVE"               numeric(38, 0),
    "IS_DELETED"              numeric(38, 0),
    "EXCEPTION_TYPE_ID"       numeric(38, 0),
    "INTRADAY_HARNESS_ID"     numeric(38, 0),
    "DQM_APP_ID"              numeric(38, 0),
    "ENVIRONMENT"             varchar(100),
    "CREATED_BY"              text,
    "CREATED_DATE"            timestamp without time zone
);

INSERT INTO public."RULE" ("RULE_NAME", "RULE_TYPE_ID", "RULE_DESCRIPTION", "RULE_COMMAND", "EXCEPTION_TYPE_ID", "ENVIRONMENT")
VALUES ('RULE_DM_BBG_MATURITY_DATE', 1, 'RULE_DM_BBG_MATURITY_DATE', 'RULE_DM_BBG_COMPARE_MATURITY_DATE', 1, 'DQM_QA');

INSERT INTO public."RULE" ("RULE_NAME", "RULE_TYPE_ID", "RULE_DESCRIPTION", "RULE_COMMAND", "EXCEPTION_TYPE_ID", "ENVIRONMENT")
VALUES ('RULE_DM_BBG_REGISTRATION', 1, 'RULE_DM_BBG_REGISTRATION', 'RULE_DM_BBG_COMPARE_REGISTRATION', 1, 'DQM_QA');
