DROP TABLE IF EXISTS public."RULE_TYPE" CASCADE;

CREATE TABLE public."RULE_TYPE" (
    "RULE_TYPE_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME"         varchar(100),
    "DESCRIPTION"  varchar(512),
    "RULE_GROUP"   integer,
    "CREATED_DATE" timestamp without time zone,
    "CREATED_BY"   varchar(100)
);

INSERT INTO public."RULE_TYPE" ("NAME", "DESCRIPTION", "RULE_GROUP", "CREATED_DATE", "CREATED_BY")
VALUES ('Bloomberg Compare Differences', 'Bloomberg Compare Differences', 1, CURRENT_TIMESTAMP, 'CORP\maliks');
