


CREATE OR REPLACE TABLE RULE  ( 
	RULE_ID                	NUMBER IDENTITY(1,1),
	RULE_TYPE_ID          	NUMBER,
	RULE_NAME              	VARCHAR(100) NULL,
	RULE_DESCRIPTION       	VARCHAR(512) NULL,
	RULE_COMMAND           	VARCHAR(1024) NULL,
	RESULT_DATE_TYPE       	VARCHAR(100) NULL,
	RULE_RESOLUTION        	VARCHAR(512) NULL,
	BUSINESS_TERM_SOURCE_ID	VARCHAR(16777216) NULL,
	IS_ACTIVE              	NUMBER(38,0) NULL,
	IS_DELETED             	NUMBER(38,0) NULL,
	EXCEPTION_TYPE_ID      	NUMBER(38,0) NULL,
	INTRADAY_HARNESS_ID    	NUMBER(38,0) NULL,
	DQM_APP_ID             	NUMBER(38,0) NULL,
    ENVIRONMENT      	VARCHAR(100) NULL,
    CREATED_BY             	VARCHAR(16777216) NULL,
	CREATED_DATE           	TIMESTAMP_NTZ(9) NULL
	)
GO


INSERT INTO RULE (RULE_NAME, RULE_TYPE_ID, RULE_DESCRIPTION, RULE_COMMAND, EXCEPTION_TYPE_ID, ENVIRONMENT)
VALUES( 'RULE_DM_BBG_MATURITY_DATE',1, 'RULE_DM_BBG_MATURITY_DATE', 'RULE_DM_BBG_COMPARE_MATURITY_DATE',1,'DQM_QA')
INSERT INTO RULE (RULE_NAME, RULE_TYPE_ID, RULE_DESCRIPTION, RULE_COMMAND, EXCEPTION_TYPE_ID, ENVIRONMENT)
VALUES( 'RULE_DM_BBG_REGISTRATION',1, 'RULE_DM_BBG_REGISTRATION', 'RULE_DM_BBG_COMPARE_REGISTRATION',1,'DQM_QA')