SELECT (6883 + 7007 + 7110) / 3.0

SELECT * FROM TCW_CORE_QA.DATA_QUALITY.RULE_GROUP

SELECT * FROM  TCW_CORE_QA.DATA_QUALITY.EXCEPTION_TYPE
SELECT * FROM TCW_CORE_QA.DATA_QUALITY.RULE

INSERT INTO TCW_CORE_QA.DATA_QUALITY.RULE(RULE_ID, CONNECTION_STRING, RULE_NAME, RULE_DESCRIPTION, RULE_COMMAND,IS_ACTIVE,EXCEPTION_TYPE_ID)
VALUES (100, 'TDC', 'DM_RULE_REGISTRATION', 'DM_RULE_REGISTRATION', 'CALL TCW_CORE_QA.DATA_QUALITY.GET_REGISTRATION', 1,1 )