CREATE OR REPLACE PROCEDURE INSERT_SECURITY_EXCEPTION(
    "SECURITY_EXCEPTION_ID" NUMBER(38,0),
    "RULE_ID"               NUMBER(38,0),
    "RUN_DATE"              TIMESTAMP,
    "RUN_START"             TIMESTAMP,
    "RUN_END"               TIMESTAMP,
    "RESULT_TYPE_ID"        NUMBER(38,0),
    "EXCEPTION_STATUS_ID"   NUMBER(38,0),
    "SEVERITY_TYPE_ID"      NUMBER(38,0),
    "PROCESS_TYPE_ID"       NUMBER(38,0),
    "CATEGORY_TYPE_ID"      NUMBER(38,0),
    "ASSIGN_TO"             VARCHAR,
    "ASSIGN_TO_DATE"        VARCHAR,
    "RESOLVE_DATE"          VARCHAR,
    "BUS_TERM_SOURCE_ID"    NUMBER(38,0),
    "ISSUE_DESCRIPTION"     VARCHAR,
    "SOURCE_SYSTEM_CODE"    VARCHAR,
    "CREATED_DATE"          TIMESTAMP,
    "CREATED_BY"            VARCHAR,
    "MODIFIED_BY"           VARCHAR,
    "MODIFIED_DATE"         TIMESTAMP,
    "EXCEPTION_SOURCE_ID"   NUMBER(38,0),
    "EXCEPTION_TYPE_ID"     NUMBER(38,0),
    "DQM_APP_ID"            NUMBER(38,0),
    "ASSET_TYPE_ID"         NUMBER(38,0),
    "ASSET"                 VARCHAR,
    "CUSIP_TYPE_CODE"       VARCHAR,
    "ASSIGNED_BY"           VARCHAR,
    "COMMENTS"              VARCHAR,
    "ALADDIN_ID"            VARCHAR(30)
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    INSERT INTO SECURITY_EXCEPTION (
        "SECURITY_EXCEPTION_ID", "RULE_ID", "RUN_DATE", "RUN_START", "RUN_END",
        "RESULT_TYPE_ID", "EXCEPTION_STATUS_ID", "SEVERITY_TYPE_ID", "PROCESS_TYPE_ID",
        "CATEGORY_TYPE_ID", "ASSIGN_TO", "ASSIGN_TO_DATE", "RESOLVE_DATE",
        "BUS_TERM_SOURCE_ID", "ISSUE_DESCRIPTION", "SOURCE_SYSTEM_CODE",
        "CREATED_DATE", "CREATED_BY", "MODIFIED_BY", "MODIFIED_DATE",
        "EXCEPTION_SOURCE_ID", "EXCEPTION_TYPE_ID", "DQM_APP_ID", "ASSET_TYPE_ID",
        "ASSET", "CUSIP_TYPE_CODE", "ASSIGNED_BY", "COMMENTS", "ALADDIN_ID"
    ) VALUES (
        :SECURITY_EXCEPTION_ID, :RULE_ID, :RUN_DATE, :RUN_START, :RUN_END,
        :RESULT_TYPE_ID, :EXCEPTION_STATUS_ID, :SEVERITY_TYPE_ID, :PROCESS_TYPE_ID,
        :CATEGORY_TYPE_ID, :ASSIGN_TO, :ASSIGN_TO_DATE, :RESOLVE_DATE,
        :BUS_TERM_SOURCE_ID, :ISSUE_DESCRIPTION, :SOURCE_SYSTEM_CODE,
        :CREATED_DATE, :CREATED_BY, :MODIFIED_BY, :MODIFIED_DATE,
        :EXCEPTION_SOURCE_ID, :EXCEPTION_TYPE_ID, :DQM_APP_ID, :ASSET_TYPE_ID,
        :ASSET, :CUSIP_TYPE_CODE, :ASSIGNED_BY, :COMMENTS, :ALADDIN_ID
    );
    RETURN 'OK';
END;
$$;
