
CREATE  OR REPLACE TABLE RULE_TYPE  (
RULE_TYPE_ID NUMBER  IDENTITY(1,1)
, NAME VARCHAR(100)
, DESCRIPTION VARCHAR(512)
, RULE_GROUP INT
, CREATED_DATE TIMESTAMP_NTZ(9)
, CREATED_BY  VARCHAR(100)
)
INSERT INTO  RULE_TYPE ( NAME, DESCRIPTION, RULE_GROUP, CREATED_DATE, CREATED_BY)
VALUES('Bloomberg Compare Differences', 'Bloomberg Compare Differences', 1, CURRENT_TIMESTAMP(), 'CORP\\maliks')

