
CREATE  OR REPLACE TABLE RULE_GROUP  (
RULE_GROUP_ID NUMBER  IDENTITY(1,1)
, NAME VARCHAR(100)
, DESCRIPTION VARCHAR(512)
, CREATED_DATE TIMESTAMP_NTZ(9)
, CREATED_BY  VARCHAR(100)
)
INSERT INTO  RULE_GROUP( NAME, DESCRIPTION, CREATED_DATE, CREATED_BY)
VALUES('Security Master', 'Security Master', CURRENT_TIMESTAMP(), 'CORP\\maliks')


