DROP TABLE IF EXISTS public."RULE_GROUP" CASCADE;

CREATE TABLE public."RULE_GROUP" (
    "RULE_GROUP_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME"          varchar(100),
    "DESCRIPTION"   varchar(512),
    "CREATED_DATE"  timestamp without time zone,
    "CREATED_BY"    varchar(100)
);

INSERT INTO public."RULE_GROUP" ("NAME", "DESCRIPTION", "CREATED_DATE", "CREATED_BY")
VALUES ('Security Master', 'Security Master', CURRENT_TIMESTAMP, 'CORP\maliks');
