--CALL TCW_CORE_QA.DATA_QUALITY.LIST_RULES('Intraday');
CREATE OR REPLACE PROCEDURE TCW_CORE_QA.DATA_QUALITY.LIST_RULES("RULE_GROUP" VARCHAR(15))
RETURNS TABLE(  "RULE_ID" INT
,"RULE_NAME" VARCHAR
, "RULE_COMMAND" VARCHAR
, "CONNECTION_STRING" VARCHAR
)
LANGUAGE SQL
execute as CALLER
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    
    res := (
         SELECT
         RULE_ID
        , RULE_NAME
       , RULE_COMMAND
       , CONNECTION_STRING
        FROM TCW_CORE_QA.DATA_QUALITY.RULE bb
        
    );

    RETURN TABLE(res);
END;
$$;

SELECT * FROM RULE