CREATE OR REPLACE PROCEDURE "LIST_RULES"("PROCESS_TYPE" VARCHAR(15))
RETURNS TABLE ("RULE_ID" NUMBER(38,0), "RULE_NAME" VARCHAR, "RULE_COMMAND" VARCHAR, "ENVIRONMENT" VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS 
DECLARE
    res RESULTSET;
BEGIN
    
    res := (
         SELECT
         RULE_ID
 
        , RULE_NAME
       , RULE_COMMAND
       , ENVIRONMENT
        FROM TCW_CORE_DEV.DATA_QUALITY.RULE bb
     --   JOIN TCW_CORE_DEV.DATA_QUALITY.RULE_GROUP rg on bb.RULE_TYPE_ID = rg.RULE_TYPE_ID
       -- WHERE RULE_GROUP = :RULE_CATEGORY
        
    );

    RETURN TABLE(res);
END;
;

--CALL LIST_RULES('INTRADAY')