--CALL TCW_CORE_DEV.DATA_QUALITY.RULE_BBG_COMPARE_MATURITY_DATE('383384LJ83', 'BBG01J6KL743')
--CALL TCW_CORE_QA.DATA_QUALITY.RULE_BBG_COMPARE_MATURITY_DATE('BDL2ZNY99', 'BBG01ZVQDZM3')

--SELECT * FROM TCW_CORE_DEV.DATA_QUALITY.SECURITY_EXCEPTION
CREATE OR REPLACE PROCEDURE TCW_CORE_DEV.DATA_QUALITY.RULE_BBG_COMPARE_MATURITY_DATE("ALADDIN_ID" VARCHAR(15), "ID_BB_GLOBAL" VARCHAR(15))
RETURNS TABLE ("ALADDIN_ID" VARCHAR, "ID_BB_GLOBAL" VARCHAR, "BBG_MATURITY_DATE" VARCHAR, "ALADDIN_MATURITY_DATE" VARCHAR, "ISSUE_DESCRIPTION" VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS 
DECLARE
    res RESULTSET;
BEGIN
    

  /*  res := (
    WITH BBG AS (
         SELECT
         HDRID
        , bbg.ID_BB_GLOBAL
         ,  COMMON.UDF_GET_BBG_MATURITY_DATE(bbg.LAST_TRADEABLE_DT, bbg.MATURITY, s.SECURITY_GROUP)  AS BBG_MATURITY_DATE
        FROM TCW_CORE_QA.COMMON.BBG_INTRADAY_SECURITY_VW bbg
        JOIN TCW_CORE_QA.TDC.SECURITY_CURRENT_VW s on bbg.ID_BB_GLOBAL = s.ID_BB_GLOBAL
        WHERE bbg.ID_BB_GLOBAL = :ID_BB_GLOBAL
        
        )
    ,
        ALADDIN AS (
         SELECT 
         ALADDIN_ID
         ,ID_BB_GLOBAL
         ,MATURITY_DATE  AS ALADDIN_MATURITY_DATE
         FROM
            TCW_CORE_QA.TDC.SECURITY_CURRENT_VW 
         WHERE ALADDIN_ID = :ALADDIN_ID
         )

         
         
        SELECT ALADDIN_ID
        , b.ID_BB_GLOBAL
        ,   BBG_MATURITY_DATE::VARCHAR(30)
        ,  ALADDIN_MATURITY_DATE::VARCHAR(30)
       ,  'BBG Vs ALADDIN Maturity Date : ALADDIN Maturity :' || ALADDIN_MATURITY_DATE ||  ' BBG Maturity:' || BBG_MATURITY_DATE   AS ISSUE_DESCRIPTION   
         FROM
        BBG b
        CROSS JOIN ALADDIN a
        WHERE IFNULL(b.BBG_MATURITY_DATE,'12/31/9999') != IFNULL(ALADDIN_MATURITY_DATE, '12/31/9999')
       
     
    );
    */
   res := (
      SELECT :ALADDIN_ID AS ALADDIN_ID
       , :ID_BB_GLOBAL::VARCHAR(30) AS ID_BB_GLOBAL
       , '04/18/2029'::VARCHAR(30) AS BBG_MATURITY_DATE
       , '05/20/2029'::VARCHAR(30) AS ALADDIN_MATURITY_DATE
       ,  'BBG Vs ALADDIN Maturity Date : ALADDIN Maturity :' || '05/20/2029' ||  ' BBG Maturity:' || '04/18/2029'   AS ISSUE_DESCRIPTION   
    );
    RETURN TABLE(res);
END;
;