CREATE OR REPLACE PROCEDURE UPDATE_EXCEPTION_STATUS(
    P_ASSET_ID VARCHAR,
    P_RULE_ID  NUMBER
)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
DECLARE
    affected NUMBER := 0;
BEGIN
    UPDATE "SECURITY_EXCEPTION"
       SET "EXCEPTION_STATUS_ID" = 4,
           "MODIFIED_DATE"       = CURRENT_TIMESTAMP::TIMESTAMP_NTZ,
           "MODIFIED_BY"         = 'system'
     WHERE "ASSET_ID"            = :P_ASSET_ID
       AND "RULE_ID"             = :P_RULE_ID
       AND "EXCEPTION_STATUS_ID" = 1;
    affected := SQLROWCOUNT;
    RETURN affected;
END;
$$;
