
CREATE OR REPLACE TABLE EXCEPTION_SEVERITY_TYPE 
(
EXCEPTION_SEVERITY_TYPE_ID INT
, NAME VARCHAR(100)
, SORT_ORDER INT
, CREATED_BY VARCHAR(100)
, CREATED_DATE TIMESTAMP_NTZ(9)
)
go
INSERT INTO EXCEPTION_SEVERITY_TYPE(EXCEPTION_SEVERITY_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
SELECT CATEGORY_TYPE_ID , CODE, SORTORDER,MODIFIED_BY, MODIFIED_DATE
FROM CATEGORY_TYPE
go

