CREATE OR REPLACE TABLE EXCEPTION_STATE
(
    EXCEPTION_STATE_ID INT
  , NAME               VARCHAR(100)
  , SORT_ORDER         INT
  , CREATED_BY         VARCHAR(100)
  , CREATED_DATE       TIMESTAMP_NTZ(9)
)
go

INSERT INTO EXCEPTION_STATE(EXCEPTION_STATE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (1, 'Pending',  10, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATE(EXCEPTION_STATE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (5, 'OnHold',   15, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATE(EXCEPTION_STATE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (2, 'Assigned', 20, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATE(EXCEPTION_STATE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (3, 'WorkedOn', 30, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATE(EXCEPTION_STATE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (4, 'Complete', 40, CURRENT_USER(), CURRENT_TIMESTAMP())
go
