CREATE OR REPLACE TABLE DATA_QUALITY.EXCEPTION
(
    EXCEPTION_ID      NUMBER IDENTITY(1000000,1)
  , RULE_ID           INT
  , ASSET_ID          VARCHAR(100)
  , EXCEPTION_DATE    DATE
  , ID_BB_GLOBAL      VARCHAR(15)
  , STATE_ID         INT
  , COMMENT_ID        INT
  , EXCEPTION_TIME    TIMESTAMP_NTZ(9)
  , ISSUE_DESCRIPTION VARCHAR(512)
  , RESULT_DATA       VARCHAR
  , SUPPRESS_DATE     DATE
  , ASSIGN_TO_ID      INT
  , RESULT_TYPE_ID    INT
  , CREATED_DATE      TIMESTAMP_NTZ(9)
  , CREATED_BY        VARCHAR(100)
  , MODIFIED_DATE     TIMESTAMP_NTZ(9)
  , MODIFIED_BY       VARCHAR(100)
)
go

INSERT INTO DATA_QUALITY.EXCEPTION (
    EXCEPTION_ID, RULE_ID, ASSET_ID, EXCEPTION_DATE, ID_BB_GLOBAL,
    STATE_ID, EXCEPTION_TIME, ISSUE_DESCRIPTION, ASSIGN_TO_ID,
    RESULT_TYPE_ID, CREATED_DATE, CREATED_BY
)
SELECT
    SECURITY_EXCEPTION_ID,
    RULE_ID,
    ASSET_ID,
    TO_DATE(RUN_DATE),
    ID_BB_GLOBAL,
    EXCEPTION_STATUS_ID,
    RUN_DATE,
    ISSUE_DESCRIPTION,
    ASSIGN_TO_ID,
    RESULT_TYPE_ID,
    CREATED_DATE,
    CREATED_BY
FROM DATA_QUALITY.SECURITY_EXCEPTION
go
