CREATE OR REPLACE TABLE EXCEPTION_STATUS
(
    EXCEPTION_STATUS_ID INT
  , NAME                VARCHAR(100)
  , SORT_ORDER          INT
  , CREATED_BY          VARCHAR(100)
  , CREATED_DATE        TIMESTAMP_NTZ(9)
)
go

INSERT INTO EXCEPTION_STATUS(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (1, 'New',       10, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATUS(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (2, 'Accept',    20, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATUS(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (3, 'Suppress',  30, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATUS(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (4, 'Challenge', 40, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATUS(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (5, 'Override',  50, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_STATUS(EXCEPTION_STATUS_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (6, 'Research',  60, CURRENT_USER(), CURRENT_TIMESTAMP())
go
