CREATE OR REPLACE TABLE EXCEPTION_TYPE
(
    EXCEPTION_TYPE_ID INT
  , NAME              VARCHAR(100)
  , SORT_ORDER        INT
  , CREATED_BY        VARCHAR(100)
  , CREATED_DATE      TIMESTAMP_NTZ(9)
)
go

INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (1, 'Security Setup',         10,  CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (2, 'Trade Queue Management', 20,  CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (3, 'Process/Workflow',       30,  CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (4, 'Corporate Actions',      40,  CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (5, 'Analytics',              50,  CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (6, 'Portfolio',              110, CURRENT_USER(), CURRENT_TIMESTAMP())
go
INSERT INTO EXCEPTION_TYPE(EXCEPTION_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
VALUES (7, 'Index',                  120, CURRENT_USER(), CURRENT_TIMESTAMP())
go
