

CREATE OR REPLACE TABLE DATA_QUALITY.EXCEPTION_HIST(
EXCEPTION_ID INT
, RULE_ID INT
, ASSET_ID VARCHAR(100)
, EXCEPTION_DATE DATE
, ID_BB_GLOBAL VARCHAR(15)
, STATUS_ID INT
, COMMENT_ID INT
, EXCEPTION_TIME TIMESTAMP_NTZ(9)
, ISSUE_DESCRIPTION VARCHAR(512)
, RESULT_DATA OBJECT
, SUPPRESS_DATE DATE
, ASSIGN_TO_ID INT
, RESULT_TYPE_ID INT
, CREATED_DATE TIMESTAMP_NTZ(9)
, CREATED_BY VARCHAR(100)
)