CREATE OR REPLACE TABLE DATA_QUALITY.EXCEPTION_HIST
(
    EXCEPTION_ID      INT
  , RULE_ID           INT
  , ASSET_ID          VARCHAR(100)
  , EXCEPTION_DATE    DATE
  , BATCH_ID          NUMBER
  , ID_BB_GLOBAL      VARCHAR(15)
  , STATE_ID         INT
  , STATUS_ID         INT
  , COMMENTS          VARCHAR(2048)
  , EXCEPTION_TIME    TIMESTAMP_NTZ(9)
  , ISSUE_DESCRIPTION VARCHAR(512)
  , RESULT_DATA       VARCHAR
  , SUPPRESS_DATE     DATE
  , OPEN_DATE         DATE
  , CLOSE_DATE        DATE
  , ASSIGN_TO_ID      INT
  , RESULT_TYPE_ID    INT
  , CREATED_DATE      TIMESTAMP_NTZ(9)
  , CREATED_BY        VARCHAR(100)
  , MODIFIED_DATE     TIMESTAMP_NTZ(9)
  , MODIFIED_BY       VARCHAR(100)
);
