--SELECT * FROM DATA_QUALITY.PRIORITY_TYPE
CREATE OR REPLACE TABLE DATA_QUALITY.EXCEPTION_PRIORITY_TYPE(
EXCEPTION_PRIORITY_TYPE_ID INT
, NAME VARCHAR(100)
, SORT_ORDER INT
, CREATED_BY VARCHAR(100)
, CREATED_DATE TIMESTAMP_NTZ(9)
)

go

INSERT INTO DATA_QUALITY.EXCEPTION_PRIORITY_TYPE(EXCEPTION_PRIORITY_TYPE_ID, NAME, SORT_ORDER,CREATED_BY, CREATED_DATE)
VALUES(1, 'High', 10, CURRENT_USER(), CURRENT_DATE())
go
INSERT INTO DATA_QUALITY.EXCEPTION_PRIORITY_TYPE(EXCEPTION_PRIORITY_TYPE_ID, NAME, SORT_ORDER,CREATED_BY, CREATED_DATE)
VALUES(2, 'Medium', 20, CURRENT_USER(), CURRENT_DATE())
go
INSERT INTO DATA_QUALITY.EXCEPTION_PRIORITY_TYPE(EXCEPTION_PRIORITY_TYPE_ID, NAME, SORT_ORDER,CREATED_BY, CREATED_DATE)
VALUES(3, 'Low', 30, CURRENT_USER(), CURRENT_DATE())
go