CREATE OR REPLACE PROCEDURE GET_RULES(
    P_PROCESS_TYPE VARCHAR,
    P_RULE_CATALOG VARCHAR DEFAULT NULL
)
RETURNS TABLE(
    "RULE_ID"      NUMBER,
    "RULE_NAME"    VARCHAR,
    "RULE_COMMAND" VARCHAR,
    "ENVIRONMENT"  VARCHAR
)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT r."RULE_ID",
               r."RULE_NAME",
               rc."RULE_CATALOG_SOURCE" AS "RULE_COMMAND",
               NULL::VARCHAR AS "ENVIRONMENT"
        FROM "RULE" r
        JOIN "RULE_CATALOG" rc ON rc."RULE_CATALOG_ID" = r."RULE_CATALOG_ID"
        WHERE (:P_RULE_CATALOG IS NULL OR :P_RULE_CATALOG = 'All' OR rc."NAME" = :P_RULE_CATALOG)
    );
    RETURN TABLE(res);
END;
$$;
