CREATE OR REPLACE PROCEDURE GET_RULE_CATALOGS(
    P_RULE_GROUP VARCHAR
)
RETURNS TABLE("RULE_CATALOG_NAME" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT rc."NAME" AS "RULE_CATALOG_NAME"
        FROM "RULE_CATALOG" rc
        JOIN "RULE_GROUP" rg
          ON rg."RULE_GROUP_ID" = rc."RULE_GROUP_ID"
        WHERE rg."NAME" = :P_RULE_GROUP
        ORDER BY rc."RULE_CATALOG_ID" ASC
    );
    RETURN TABLE(res);
END;
$$;
