CREATE OR REPLACE PROCEDURE GET_PRIORITY_TYPE()
RETURNS TABLE("NAME" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "NAME"
        FROM "EXCEPTION_PRIORITY_TYPE"
        ORDER BY "SORT_ORDER" ASC, "NAME" ASC
    );
    RETURN TABLE(res);
END;
$$;
