INSERT INTO DATA_QUALITY.EXCEPTION_HIST (
    EXCEPTION_ID, RULE_ID, ASSET_ID, EXCEPTION_DATE, ID_BB_GLOBAL,
    STATUS_ID, COMMENT_ID, EXCEPTION_TIME, ISSUE_DESCRIPTION,
    RESULT_DATA, SUPPRESS_DATE, ASSIGN_TO_ID, RESULT_TYPE_ID,
    CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY
)
SELECT
    EXCEPTION_ID, RULE_ID, ASSET_ID, EXCEPTION_DATE, ID_BB_GLOBAL,
    STATUS_ID, COMMENT_ID, EXCEPTION_TIME, ISSUE_DESCRIPTION,
    RESULT_DATA, SUPPRESS_DATE, ASSIGN_TO_ID, RESULT_TYPE_ID,
    CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY
FROM DATA_QUALITY.EXCEPTION;
