INSERT INTO DATA_QUALITY.EXCEPTION (
    EXCEPTION_ID, RULE_ID, ASSET_ID, EXCEPTION_DATE, ID_BB_GLOBAL,
    STATE_ID, EXCEPTION_TIME, ISSUE_DESCRIPTION, ASSIGN_TO_ID,
    RESULT_TYPE_ID, CREATED_DATE, CREATED_BY
)
SELECT
    SECURITY_EXCEPTION_ID,
    RULE_ID,
    ASSET_ID,
    TO_DATE(RUN_DATE),
    ID_BB_GLOBAL,
    EXCEPTION_STATUS_ID,
    RUN_DATE,
    ISSUE_DESCRIPTION,
    ASSIGN_TO_ID,
    RESULT_TYPE_ID,
    CREATED_DATE,
    CREATED_BY
FROM DATA_QUALITY.SECURITY_EXCEPTION;
