
CREATE OR REPLACE TABLE PROCESS_TYPE_2 
(
PROCESS_TYPE_ID INT
, NAME VARCHAR(100)
, SORT_ORDER INT
, CREATED_BY VARCHAR(100)
, CREATED_DATE TIMESTAMP_NTZ(9)
)
go
INSERT INTO PROCESS_TYPE_2(PROCESS_TYPE_ID, NAME, SORT_ORDER, CREATED_BY, CREATED_DATE)
SELECT PROCESS_TYPE_ID , CODE, SORT_ORDER,MODIFIED_BY, MODIFIED_DATE
FROM PROCESS_TYPE
go


