
CREATE OR REPLACE  TABLE RULE_2  ( 
	RULE_ID                NUMBER IDENTITY(1,1),
	RULE_CATALOG_ID           	INT NULL,
	RULE_NAME              	VARCHAR(100) NULL,
	RULE_DESCRIPTION       	VARCHAR(512) NULL,
	IS_ACTIVE              	NUMBER(38,0) NULL,
	EXCEPTION_TYPE_ID      	NUMBER(38,0) NULL,
	EXCEPTION_PROCESS_TYPE_ID NUMBER NULL,
	EXCEPTION_SEVERITY_TYPE_ID NUMBER NULL,
	EXCEPTION_PRIORITY_TYPE_ID NUMBER NULL,
	EXCEPTION_SOURCE NUMBER NULL,
	CREATED_BY             	VARCHAR(100) NULL,
	CREATED_DATE           	TIMESTAMP_NTZ(9) NULL 
	)
GO

INSERT INTO RULE_2(RULE_CATALOG_ID,RULE_NAME,RULE_DESCRIPTION,IS_ACTIVE,	EXCEPTION_TYPE_ID , 
	EXCEPTION_PROCESS_TYPE_ID ,
	EXCEPTION_SEVERITY_TYPE_ID ,
	EXCEPTION_PRIORITY_TYPE_ID ,
	EXCEPTION_SOURCE ,
	CREATED_BY  ,
	CREATED_DATE )
VALUES(1, 'RULE_DM_BBG_MATURITY_DATE', 'Compares Maturity Date between Bloomberg and Aladdin', 1, 1, 1,1,2, 1, CURRENT_USER(), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9)  )

go
INSERT INTO RULE_2(RULE_CATALOG_ID,RULE_NAME,RULE_DESCRIPTION,IS_ACTIVE,	EXCEPTION_TYPE_ID , 
	EXCEPTION_PROCESS_TYPE_ID ,
	EXCEPTION_SEVERITY_TYPE_ID ,
	EXCEPTION_PRIORITY_TYPE_ID ,
	EXCEPTION_SOURCE ,
	CREATED_BY  ,
	CREATED_DATE )
VALUES(1, 'RULE_DM_BBG_REGISTRATION', 'Compares Registration between Bloomberg and Aladdin', 1, 1, 1,1,2, 1, CURRENT_USER(), CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9)  )
go
/*
SELECT * FROM EXCEPTION_TYPE
SELECT * FROM EXCEPTION_PROCESS_TYPE
SELECT * FROM EXCEPTION_SEVERITY_TYPE
SELECT * FROM EXCEPTION_PRIORITY_TYPE
SELECT * FROM EXCEPTION_SOURCE
SELECT * FROM EXCEPTION_CATEGORY_TYPE

SELECT * FROM RULE
*/
