
CREATE OR REPLACE TABLE RULE_CATALOG  (
    RULE_CATALOG_ID                	NUMBER(38,0) IDENTITY(1,1),
	NAME         	VARCHAR(100) NULL,
	DESCRIPTION  	VARCHAR(512) NULL,
	RULE_GROUP_ID	NUMBER(38,0) NULL,
	RULE_CATALOG_SOURCE VARCHAR(4096),
	RULE_CATALOG_TYPE VARCHAR(100),
	RULE_CATALOG_CONNECTION VARCHAR(1000),
	REVERT_TO_NEW_CRITERIA VARCHAR(200),
	CREATED_DATE 	TIMESTAMP_NTZ(9) NULL,
	CREATED_BY   	VARCHAR(100) NULL
	)
GO
INSERT INTO RULE_CATALOG(NAME, DESCRIPTION, RULE_GROUP_ID,RULE_CATALOG_SOURCE, RULE_CATALOG_TYPE, RULE_CATALOG_CONNECTION,CREATED_DATE, CREATED_BY)
SELECT  NAME, DESCRIPTION, RULE_GROUP_ID,NULL, NULL, NULL,CREATED_DATE, CREATED_BY  FROM RULE_TYPE
go

UPDATE RULE_CATALOG 
SET RULE_CATALOG_SOURCE = 'SELECT * FROM COMMON.RECON_BBG_COMPARE_VW'
, RULE_CATALOG_TYPE = 'SQL'
, RULE_CATALOG_CONNECTION = 'DE_SNOWFLAKE'