CREATE OR REPLACE PROCEDURE SP_GET_DM_USERS()
RETURNS TABLE("USER" VARCHAR, "ROLE" VARCHAR, "EMAIL" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "USER", "ROLE", "EMAIL"
        FROM "DM_USER"
        ORDER BY "ID" ASC
    );
    RETURN TABLE(res);
END;
$$;
