CREATE OR REPLACE PROCEDURE SP_GET_RULE_GROUPS()
RETURNS TABLE("NAME" VARCHAR, "FLAG_STATUS_VISIBLE" BOOLEAN, "FLAG_COMMENTS_VISIBLE" BOOLEAN)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "NAME",
               COALESCE("FLAG_STATUS_VISIBLE",   FALSE) AS "FLAG_STATUS_VISIBLE",
               COALESCE("FLAG_COMMENTS_VISIBLE", FALSE) AS "FLAG_COMMENTS_VISIBLE"
        FROM "RULE_GROUP"
        ORDER BY "RULE_GROUP_ID" ASC
    );
    RETURN TABLE(res);
END;
$$;
