CREATE OR REPLACE PROCEDURE SP_GET_RULE_GROUPS()
RETURNS TABLE("NAME" VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
    res RESULTSET;
BEGIN
    res := (
        SELECT "NAME"
        FROM "RULE_GROUP"
        ORDER BY "RULE_GROUP_ID" ASC
    );
    RETURN TABLE(res);
END;
$$;
