CREATE OR REPLACE PROCEDURE SP_INSERT_SECURITY_EXCEPTION(
    "RULE_ID"               NUMBER,
    "RUN_DATE"              TIMESTAMP_NTZ,
    "RUN_START"             TIMESTAMP_NTZ,
    "RUN_END"               TIMESTAMP_NTZ,
    "RESULT_TYPE_ID"        NUMBER,
    "EXCEPTION_STATUS_ID"   NUMBER,
    "SEVERITY_TYPE_ID"      NUMBER,
    "PROCESS_TYPE_ID"       NUMBER,
    "CATEGORY_TYPE_ID"      NUMBER,
    "ASSIGN_TO_ID"          NUMBER,
    "ASSIGN_TO_DATE"        VARCHAR,
    "RESOLVE_DATE"          VARCHAR,
    "BUS_TERM_SOURCE_ID"    NUMBER,
    "ISSUE_DESCRIPTION"     VARCHAR,
    "SOURCE_SYSTEM_CODE"    VARCHAR,
    "CREATED_DATE"          TIMESTAMP_NTZ,
    "CREATED_BY"            VARCHAR,
    "MODIFIED_BY"           VARCHAR,
    "MODIFIED_DATE"         TIMESTAMP_NTZ,
    "EXCEPTION_SOURCE_ID"   NUMBER,
    "EXCEPTION_TYPE_ID"     NUMBER,
    "DQM_APP_ID"            NUMBER,
    "ASSET_TYPE_ID"         NUMBER,
    "ASSET"                 VARCHAR,
    "CUSIP_TYPE_CODE"       VARCHAR,
    "ASSIGNED_BY"           VARCHAR,
    "COMMENTS"              VARCHAR,
    "ASSET_ID"              VARCHAR,
    "ID_BB_GLOBAL"          VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO "SECURITY_EXCEPTION" (
        "RULE_ID", "RUN_DATE", "RUN_START", "RUN_END",
        "RESULT_TYPE_ID", "EXCEPTION_STATUS_ID", "SEVERITY_TYPE_ID", "PROCESS_TYPE_ID",
        "CATEGORY_TYPE_ID", "ASSIGN_TO_ID", "ASSIGN_TO_DATE", "RESOLVE_DATE",
        "BUS_TERM_SOURCE_ID", "ISSUE_DESCRIPTION", "SOURCE_SYSTEM_CODE",
        "CREATED_DATE", "CREATED_BY", "MODIFIED_BY", "MODIFIED_DATE",
        "EXCEPTION_SOURCE_ID", "EXCEPTION_TYPE_ID", "DQM_APP_ID", "ASSET_TYPE_ID",
        "ASSET", "CUSIP_TYPE_CODE", "ASSIGNED_BY", "COMMENTS", "ASSET_ID",
        "ID_BB_GLOBAL"
    ) VALUES (
        :RULE_ID, :RUN_DATE, :RUN_START, :RUN_END,
        :RESULT_TYPE_ID,
        COALESCE(NULLIF(:EXCEPTION_STATUS_ID, 0), 1),  -- default to Pending
        :SEVERITY_TYPE_ID, :PROCESS_TYPE_ID,
        :CATEGORY_TYPE_ID, :ASSIGN_TO_ID, :ASSIGN_TO_DATE, :RESOLVE_DATE,
        :BUS_TERM_SOURCE_ID, :ISSUE_DESCRIPTION, :SOURCE_SYSTEM_CODE,
        :CREATED_DATE, :CREATED_BY, :MODIFIED_BY, :MODIFIED_DATE,
        :EXCEPTION_SOURCE_ID, :EXCEPTION_TYPE_ID, :DQM_APP_ID, :ASSET_TYPE_ID,
        :ASSET, :CUSIP_TYPE_CODE, :ASSIGNED_BY, :COMMENTS, :ASSET_ID,
        :ID_BB_GLOBAL
    );
    RETURN 'OK';
END;
$$;
