CREATE OR REPLACE PROCEDURE SP_UPDATE_EXCEPTION_SUPPRESS_DATE(
    P_EXCEPTION_ID  NUMBER,
    P_SUPPRESS_DATE DATE
)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
DECLARE
    affected NUMBER := 0;
BEGIN
    UPDATE "EXCEPTION"
       SET "SUPPRESS_DATE" = :P_SUPPRESS_DATE,
           "MODIFIED_DATE" = CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ,
           "MODIFIED_BY"   = 'system'
     WHERE "EXCEPTION_ID" = :P_EXCEPTION_ID;
    affected := SQLROWCOUNT;
    RETURN affected;
END;
$$;
