CREATE OR REPLACE PROCEDURE UPDATE_EXCEPTION_STATUS(
    P_ASSET_ID VARCHAR,
    P_RULE_ID  NUMBER,
    P_COMPLETE BOOLEAN DEFAULT FALSE
)
RETURNS NUMBER
LANGUAGE SQL
AS
$$
DECLARE
    affected NUMBER := 0;
BEGIN
    UPDATE "EXCEPTION"
       SET "STATUS_ID"     = CASE WHEN :P_COMPLETE THEN 4 ELSE "STATUS_ID" END,
           "MODIFIED_DATE" = CURRENT_TIMESTAMP::TIMESTAMP_NTZ,
           "MODIFIED_BY"   = 'system'
     WHERE "ASSET_ID"      = :P_ASSET_ID
       AND "RULE_ID"       = :P_RULE_ID;
    affected := SQLROWCOUNT;
    RETURN affected;
END;
$$;
