CREATE OR REPLACE PROCEDURE UPDATE_EXCEPTION(
    P_RULE_ID           NUMBER,
    P_ASSET_ID          VARCHAR,
    P_EXCEPTION_DATE    DATE,
    P_ID_BB_GLOBAL      VARCHAR,
    P_STATUS_ID         NUMBER,
    P_EXCEPTION_TIME    TIMESTAMP_NTZ,
    P_ISSUE_DESCRIPTION VARCHAR,
    P_RESULT_DATA       OBJECT,
    P_ASSIGN_TO_ID      NUMBER,
    P_RESULT_TYPE_ID    NUMBER,
    P_CREATED_DATE      TIMESTAMP_NTZ,
    P_CREATED_BY        VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE "EXCEPTION"
       SET "EXCEPTION_DATE"    = :P_EXCEPTION_DATE,
           "EXCEPTION_TIME"    = :P_EXCEPTION_TIME,
           "STATUS_ID"         = 1,  -- re-flagged → Pending
           "ISSUE_DESCRIPTION" = :P_ISSUE_DESCRIPTION,
           "RESULT_DATA"       = COALESCE(:P_RESULT_DATA, "RESULT_DATA"),
           "ASSIGN_TO_ID"      = COALESCE(:P_ASSIGN_TO_ID, "ASSIGN_TO_ID"),
           "RESULT_TYPE_ID"    = :P_RESULT_TYPE_ID,
           "CREATED_DATE"      = :P_CREATED_DATE,
           "CREATED_BY"        = :P_CREATED_BY,
           "ID_BB_GLOBAL"      = COALESCE(:P_ID_BB_GLOBAL, "ID_BB_GLOBAL")
     WHERE "ASSET_ID" = :P_ASSET_ID
       AND "RULE_ID"  = :P_RULE_ID;
    RETURN 'OK';
END;
$$;
