// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/api/events": {
            "get": {
                "description": "Long-lived text/event-stream that pushes events such as security_exception.inserted to subscribed clients.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Server-Sent Events stream of domain changes",
                "responses": {
                    "200": {
                        "description": "stream of SSE-formatted events",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/api/executeRules": {
            "post": {
                "description": "Moves today's EXCEPTION rows for the catalogs implied by (rule_name, rule_type) into EXCEPTION_HIST via SP_ARCHIVE_EXCEPTIONS (each row stamped with a per-EXCEPTION_DATE BATCH_ID that starts at 1 for a new day and increments for subsequent same-day runs), then runs every matching catalog and inserts whatever rows the catalog sources return. Per-asset scoping (asset_id / id_bb_global) is intentionally not accepted — use /executeSecurityRules for that. rule_name + rule_type semantics match /getRules (\"CATALOG\" / \"RULE\" match RULE_CATALOG.NAME, \"GROUP\" matches RULE_GROUP.NAME, omit / empty / \"All\" runs every catalog). is_refresh (default \"Y\") is substituted into any ${IS_REFRESH} placeholder in the RULE_CATALOG_SOURCE as a single-quoted 'Y' / 'N' literal, ready for a VARCHAR proc param. ` + "`" + `params` + "`" + ` in the request body is an optional map of ${NAME} placeholder substitutions — e.g. {\"RATINGS_MISSING\":\"Aa\"} substitutes ${RATINGS_MISSING} → 'Aa'; empty values become SQL NULL. Blocks until the run completes — a Security Master GROUP run against Snowflake can take several minutes; the front-of-service proxy (nginx) must have ` + "`" + `proxy_read_timeout` + "`" + ` set high enough to cover it (300s+ is safe). Response is always an ExecuteRulesResponse: exception_count is the number of rows inserted this run, exception_message carries the backend error text on non-2xx, and exception_status mirrors the HTTP status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Execute rules (archive-then-insert)",
                "parameters": [
                    {
                        "description": "rule_name / rule_type / is_refresh scope + optional params bag",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExecuteRulesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rules executed; exception_count = rows inserted",
                        "schema": {
                            "$ref": "#/definitions/models.ExecuteRulesResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/models.ExecuteRulesResponse"
                        }
                    },
                    "404": {
                        "description": "requested rule / catalog / group not found",
                        "schema": {
                            "$ref": "#/definitions/models.ExecuteRulesResponse"
                        }
                    },
                    "500": {
                        "description": "failed to execute rules",
                        "schema": {
                            "$ref": "#/definitions/models.ExecuteRulesResponse"
                        }
                    }
                }
            }
        },
        "/v1/api/executeSN": {
            "post": {
                "description": "QA / debugging helper. Executes the caller-supplied ` + "`" + `sn_sql` + "`" + ` verbatim on the live Snowflake connection and returns any row set produced (as an array of column→string maps; nulls come back as JSON null). Postgres is intentionally not implemented — returns 500 with \"not implemented\" so this endpoint can't accidentally run SQL against local dev data. Result set is capped at 1000 rows to keep an unbounded SELECT from streaming the whole warehouse. Will be removed once no longer needed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maintenance"
                ],
                "summary": "TEMPORARY: run arbitrary SQL on Snowflake",
                "parameters": [
                    {
                        "description": "SQL to run on Snowflake",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.executeSNBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "row_count + rows (may be empty for DDL)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "invalid request body / empty sql",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "execution failed or not implemented for this database",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/executeSecurityRules": {
            "get": {
                "description": "Same orchestration as /executeRules but routed through services.ExecuteSecurityRules so the security-rule flow can diverge later. Query params are identical: asset_id is optional (required when id_bb_global is supplied); rule_name + rule_type scope which catalogs run (\"CATALOG\" / \"RULE\" match RULE_CATALOG.NAME, \"GROUP\" matches RULE_GROUP.NAME, omit / empty / \"All\" runs every catalog).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Execute security rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID (omit to run across all assets; required when id_bb_global is supplied)",
                        "name": "asset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bloomberg global ID",
                        "name": "id_bb_global",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter value (catalog name or group name depending on rule_type)",
                        "name": "rule_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "CATALOG | GROUP | RULE",
                        "name": "rule_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "security rules executed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "asset_id is required when id_bb_global is supplied",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to execute security rules",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getAssets": {
            "get": {
                "description": "Returns the deduplicated set of assets, optionally filtered by exception type CODE and severity (CATEGORY_TYPE.CODE).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "List assets with exception summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "EXCEPTION_TYPE.CODE filter",
                        "name": "exception_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "CATEGORY_TYPE.CODE filter",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "SEVERITY_TYPE.CODE filter",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE_CATALOG.NAME filter",
                        "name": "rule_catalog",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE.RULE_NAME filter",
                        "name": "rule_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_STATE.CODE filter",
                        "name": "exception_state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "DM_USER.USER filter",
                        "name": "assign_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Asset"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query assets",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getDMRole": {
            "get": {
                "description": "Returns { \"role\": \"\u003cDM_USER.ROLE\u003e\" } for the given\nDM_USER.USER value. Unknown user → role: \"\". Powers\nthe frontend gate that hides Bulk Assign / Bulk\nStatus buttons and locks the per-row Assign To\ncolumn when the current operator isn't DM_ADMIN.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the DM role for one user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DM_USER.USER",
                        "name": "user",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "user is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query role",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getDMUsers": {
            "get": {
                "description": "Returns DM_USER rows as {user, role, email} tuples,\nordered by ID. Row 0 is the \"Unassigned\" placeholder\n(role + email come back empty).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List DM users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.DMUser"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query users",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptionCountsByGroup": {
            "get": {
                "description": "Aggregation-only counterpart to /getExceptions: returns\none {rule_group, count} row per group with matching\nEXCEPTION rows after applying the same predicates the\ncount panel uses (exception_type, severity, priority,\nexception_state, assign_to). Status filter is not\napplied — the count panel's \"All\" summary is unfiltered\nby status. Powers the count-panel single-call path\nthat replaces the earlier N-call fetchExceptions fanout.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Count of EXCEPTION rows per RULE_GROUP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exception type filter",
                        "name": "exception_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Severity filter",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Priority filter",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exception state filter",
                        "name": "exception_state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Assign-to filter",
                        "name": "assign_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.GroupCount"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exception counts by group",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptionHistDates": {
            "get": {
                "description": "Returns ISO date strings for the last 60 days that have any\nEXCEPTION_HIST activity, most recent first. Powers the\n\"DQM Date\" dropdown options.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Distinct EXCEPTION_DATEs available in EXCEPTION_HIST",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exception history dates",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptionState": {
            "get": {
                "description": "Returns EXCEPTION_STATE.CODE values ordered by SORT_ORDER.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exception-state"
                ],
                "summary": "List exception state codes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exception state",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptionStatus": {
            "get": {
                "description": "Returns EXCEPTION_STATUS.NAME values ordered by SORT_ORDER.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exception-status"
                ],
                "summary": "List exception status names",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exception status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptionTypes": {
            "get": {
                "description": "Returns EXCEPTION_TYPE.NAME values ordered by SORT_ORDER.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exception-types"
                ],
                "summary": "List exception type names",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exception types",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptions": {
            "get": {
                "description": "Returns rows from GET_EXCEPTIONS, which reads the slim EXCEPTION table joined with RULE and the EXCEPTION_*_TYPE lookups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "List exceptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID filter",
                        "name": "asset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_TYPE.NAME filter",
                        "name": "exception_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_SEVERITY_TYPE.NAME filter",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_PRIORITY_TYPE.NAME filter",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE_CATALOG.NAME filter (reserved — RULE does not carry RULE_CATALOG_ID for filtering yet)",
                        "name": "rule_catalog",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE.RULE_NAME filter",
                        "name": "rule_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Reserved (RULE has no rule_group yet)",
                        "name": "rule_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_STATE.NAME filter",
                        "name": "exception_state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "DM_USER.USER filter",
                        "name": "assign_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "SQL ILIKE pattern against RULE.RULE_NAME",
                        "name": "rule_name_pattern",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Exception"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exceptions",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getExceptionsHist": {
            "get": {
                "description": "Same shape as /getExceptions but reads from EXCEPTION_HIST\nand only returns rows belonging to that day's LATEST BATCH_ID\nwithin the caller's rule/catalog/group scope. Powers the \"DQM\nDate\" back-in-time selector on the sidebar.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "List history-table exceptions for a specific EXCEPTION_DATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ISO YYYY-MM-DD",
                        "name": "exception_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Asset ID filter",
                        "name": "asset_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_TYPE.NAME filter",
                        "name": "exception_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_SEVERITY_TYPE.NAME filter",
                        "name": "severity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_PRIORITY_TYPE.NAME filter",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE_CATALOG.NAME filter",
                        "name": "rule_catalog",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE.RULE_NAME filter",
                        "name": "rule_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RULE_GROUP.NAME filter",
                        "name": "rule_group",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_STATE.NAME filter",
                        "name": "exception_state",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "DM_USER.USER filter",
                        "name": "assign_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "SQL ILIKE pattern against RULE.RULE_NAME",
                        "name": "rule_name_pattern",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Exception"
                            }
                        }
                    },
                    "400": {
                        "description": "exception_date is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query exception history",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getPriorityTypes": {
            "get": {
                "description": "Returns EXCEPTION_PRIORITY_TYPE.NAME values ordered by SORT_ORDER.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "priority-types"
                ],
                "summary": "List priority names",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query priority types",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getRuleCatalogs": {
            "get": {
                "description": "Returns RULE_CATALOG.NAME values joined to RULE_GROUP by RULE_GROUP_ID and filtered by rule group name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule-catalogs"
                ],
                "summary": "List rule type names for a rule group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule group name",
                        "name": "rule_group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "rule_group query parameter is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query rule types",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getRuleGroups": {
            "get": {
                "description": "Returns RULE_GROUP rows (name + flag_status_visible) ordered by RULE_GROUP_ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule-groups"
                ],
                "summary": "List rule groups",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RuleGroup"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query rule groups",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getRuleGroupsForUser": {
            "get": {
                "description": "Same shape as /getRuleGroups but filtered via\nRULE_GROUP_AUTHORIZATION.ACCESS_LIST — only groups whose\naccess list contains the user's DM_USER.EMAIL are\nreturned. Powers the LHS tree view. Unknown user / no\nemail / no auth row → empty array (least-privileged).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule-groups"
                ],
                "summary": "List rule groups the given operator is authorized to see",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DM_USER display name",
                        "name": "user",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RuleGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "user is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query rule groups for user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getRuleNames": {
            "get": {
                "description": "Returns one {rule_name, rule_description} per RULE row in the given catalog. Used by the rule tree view to render the friendlier description on each leaf (falling back to rule_name when null/empty) and to label the Exceptions header when a specific rule is selected.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rule-names"
                ],
                "summary": "List rule names + descriptions for a catalog",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule catalog name",
                        "name": "rule_catalog",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RuleName"
                            }
                        }
                    },
                    "400": {
                        "description": "rule_catalog query parameter is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query rule names",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getRules": {
            "get": {
                "description": "Returns one row per RULE_CATALOG, optionally filtered. rule_type controls how rule_name is interpreted: \"CATALOG\" or \"RULE\" -\u003e rule_name matches RULE_CATALOG.NAME; \"GROUP\" -\u003e rule_name matches RULE_GROUP.NAME. Omit / empty / \"All\" means no filter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "List rule catalogs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter value (catalog name or group name depending on rule_type)",
                        "name": "rule_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "CATALOG | GROUP | RULE",
                        "name": "rule_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rule"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query rules",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getRulesForGroup": {
            "get": {
                "description": "Returns one row per active RULE under the given RULE_GROUP,\nprojected as (rule_name, catalog_name, rule_description).\nCollapses the LHS tree's earlier N+1 fanout\n(getRuleCatalogs + getRuleNames per catalog) into a single\ncall — powers the count panel's ruleName→catalog map and\nthe rule-description hover cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "List every active RULE under a group with its catalog + description",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule group name",
                        "name": "rule_group",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RuleForGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "rule_group query parameter is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query rules for group",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/getSeverityTypes": {
            "get": {
                "description": "Returns CATEGORY_TYPE.CODE values ordered by CATEGORY_RANK.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "severity-types"
                ],
                "summary": "List severity codes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to query severity types",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/info": {
            "get": {
                "description": "Returns a static welcome string used as a basic liveness check.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Service welcome message",
                "responses": {
                    "200": {
                        "description": "Welcome to Go microservices using Fiber",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/api/junk": {
            "post": {
                "description": "QA reset helper. Runs TRUNCATE TABLE against EXCEPTION and EXCEPTION_HIST on Snowflake so a test run can start from an empty state. Postgres is intentionally not implemented — returns 500 with \"not implemented\" if the deployed database is Postgres so this can't accidentally wipe local dev data. Will be removed once the QA reset workflow no longer needs it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maintenance"
                ],
                "summary": "TEMPORARY: truncate EXCEPTION and EXCEPTION_HIST (Snowflake only)",
                "responses": {
                    "200": {
                        "description": "tables truncated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "truncate failed or not implemented for this database",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateAssignTo": {
            "get": {
                "description": "Resolves assign_to against DM_USER and updates every",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Update EXCEPTION.ASSIGN_TO_ID for an asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "asset_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "DM_USER.USER name (empty to unassign)",
                        "name": "assign_to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "asset_id query parameter is required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update assign to",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateBulkAssign": {
            "post": {
                "description": "Updates EXCEPTION.ASSIGN_TO_ID for every existing exception\nwhose RULE_NAME matches. When is_permanent is false (default),\nalso writes one RULE_ASSIGN_OVERRIDE row per rule so\nsubsequent rule runs inherit the assignee via the rao join.\nWhen is_permanent is true, RULE.ASSIGN_TO_ID itself is\nupdated for every matched rule and no override row is\nwritten. Rule names + assignee name are resolved\nserver-side via DM_USER.\"USER\" / RULE.\"RULE_NAME\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Bulk-assign a user to every EXCEPTION under the passed rules",
                "parameters": [
                    {
                        "description": "rule_names + assign_to + is_permanent",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateBulkAssignBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update bulk assign",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateBulkStatus": {
            "post": {
                "description": "Resolves rule names → RULE_IDs, resolves status name →\nEXCEPTION_STATUS_ID, then updates EXCEPTION.STATUS_ID\n(and EXCEPTION.COMMENTS when comments is non-null) for\nevery row whose RULE_ID falls in the resolved set.\nComments set to null in the JSON body leaves the\nexisting COMMENTS untouched; empty string clears them.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Bulk-set STATUS + COMMENTS on every EXCEPTION under the passed rules",
                "parameters": [
                    {
                        "description": "rule_names + status + comments",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateBulkStatusBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update bulk status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateExceptionAssignTo": {
            "post": {
                "description": "Resolves assign_to against DM_USER and updates the single\nEXCEPTION row keyed by exception_id. Empty assign_to clears\nthe assignment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Update EXCEPTION.ASSIGN_TO_ID for a single row",
                "parameters": [
                    {
                        "description": "exception_id + assign_to",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateExceptionAssignToBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update exception assign_to",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateExceptionComments": {
            "post": {
                "description": "Sets the free-text COMMENTS on the row identified by exception_id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Update EXCEPTION.COMMENTS for a single row",
                "parameters": [
                    {
                        "description": "exception_id + comments",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateExceptionCommentsBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update exception comments",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateExceptionStatus": {
            "get": {
                "description": "Resolves the status name against EXCEPTION_STATUS and updates\nthe STATUS_ID for the row identified by exception_id. Optional\ncomments + suppress_date get bundled into the same UPDATE so\nthe SP's \"blank\" guards check the effective (passed) value\ninstead of a stale DB value the operator hasn't committed yet.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Update EXCEPTION.STATUS_ID for a single row",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "EXCEPTION_ID",
                        "name": "exception_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "EXCEPTION_STATUS.NAME",
                        "name": "status",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Pending COMMENTS to apply alongside the status change (empty = leave alone)",
                        "name": "comments",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pending SUPPRESS_DATE (YYYY-MM-DD) to apply alongside the status change (empty = leave alone)",
                        "name": "suppress_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update exception status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/api/updateExceptionSuppressDate": {
            "post": {
                "description": "Sets the SUPPRESS_DATE (YYYY-MM-DD) on the row identified by\nexception_id. Empty suppress_date clears the cell.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exceptions"
                ],
                "summary": "Update EXCEPTION.SUPPRESS_DATE for a single row",
                "parameters": [
                    {
                        "description": "exception_id + suppress_date",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateExceptionSuppressDateBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rows updated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "invalid params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "failed to update exception suppress_date",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.executeSNBody": {
            "type": "object",
            "properties": {
                "sn_sql": {
                    "description": "Raw SQL to run against Snowflake. Anything the driver accepts:\nDDL (CREATE / DROP / ALTER), DML, CALL \u003cprocedure\u003e, SELECT.",
                    "type": "string",
                    "example": "CALL SP_ARCHIVE_STALE_DATES()"
                }
            }
        },
        "handlers.updateBulkAssignBody": {
            "type": "object",
            "properties": {
                "assign_to": {
                    "type": "string"
                },
                "is_permanent": {
                    "type": "boolean"
                },
                "rule_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.updateBulkStatusBody": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "rule_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "suppress_date": {
                    "type": "string"
                }
            }
        },
        "handlers.updateExceptionAssignToBody": {
            "type": "object",
            "properties": {
                "assign_to": {
                    "type": "string"
                },
                "exception_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.updateExceptionCommentsBody": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "string"
                },
                "exception_id": {
                    "type": "integer"
                }
            }
        },
        "handlers.updateExceptionSuppressDateBody": {
            "type": "object",
            "properties": {
                "exception_id": {
                    "type": "integer"
                },
                "suppress_date": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "type": "object",
            "properties": {
                "all_complete": {
                    "type": "boolean"
                },
                "asset_id": {
                    "type": "string"
                },
                "assign_to": {
                    "type": "string"
                },
                "bbg_last_refresh": {
                    "type": "string"
                },
                "exception_count": {
                    "type": "integer"
                },
                "exception_date": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "security_description": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "trader": {
                    "type": "string"
                },
                "trading_team": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.DMUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "models.Exception": {
            "type": "object",
            "properties": {
                "asset_id": {
                    "type": "string"
                },
                "assign_to": {
                    "type": "string"
                },
                "assign_to_id": {
                    "type": "integer"
                },
                "close_date": {
                    "type": "string"
                },
                "comments": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "created_date": {
                    "type": "string"
                },
                "exception_date": {
                    "type": "string"
                },
                "exception_id": {
                    "type": "integer"
                },
                "exception_state": {
                    "type": "string"
                },
                "exception_status": {
                    "type": "string"
                },
                "exception_time": {
                    "type": "string"
                },
                "exception_type": {
                    "type": "string"
                },
                "id_bb_global": {
                    "type": "string"
                },
                "issue_description": {
                    "type": "string"
                },
                "modified_by": {
                    "type": "string"
                },
                "modified_date": {
                    "type": "string"
                },
                "open_date": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "result_data": {
                    "type": "string"
                },
                "result_type_id": {
                    "type": "integer"
                },
                "rule_id": {
                    "type": "integer"
                },
                "rule_name": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "state_id": {
                    "type": "integer"
                },
                "status_id": {
                    "type": "integer"
                },
                "suppress_date": {
                    "type": "string"
                }
            }
        },
        "models.ExecuteRulesRequest": {
            "type": "object",
            "properties": {
                "is_refresh": {
                    "description": "'Y' or 'N' — substituted into any ${IS_REFRESH} placeholder in\nthe RULE_CATALOG_SOURCE. Defaults to 'Y' when empty.",
                    "type": "string",
                    "enum": [
                        "Y",
                        "N"
                    ],
                    "example": "Y"
                },
                "params": {
                    "description": "Extra ${NAME} placeholder substitutions keyed by placeholder name\n(upper-cased, no ${…}). Optional. Empty values become SQL NULL.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "rule_name": {
                    "description": "Filter value. When RuleType is CATALOG or RULE it matches\nRULE_CATALOG.NAME (or RULE.RULE_NAME under RULE); under GROUP it\nmatches RULE_GROUP.NAME. Empty or \"All\" runs every catalog.",
                    "type": "string",
                    "example": "Security Master"
                },
                "rule_type": {
                    "description": "One of CATALOG | GROUP | RULE. Empty is equivalent to CATALOG.",
                    "type": "string",
                    "enum": [
                        "CATALOG",
                        "GROUP",
                        "RULE"
                    ],
                    "example": "GROUP"
                }
            }
        },
        "models.ExecuteRulesResponse": {
            "type": "object",
            "properties": {
                "exception_count": {
                    "description": "Total number of exceptions inserted by this run (i.e. len(produced)\nafter every catalog in scope ran and the archive-then-insert\npipeline finished). Zero when the scope resolves to no catalogs\nor when a catalog failed before insert.",
                    "type": "integer",
                    "example": 280
                },
                "exception_message": {
                    "description": "Human-readable failure detail. Always present in the JSON — an\nempty string on success, populated with the wrapped error\nmessage on 404 (bad scope) and 500 (Snowflake / SP failure).\nKept unconditionally (no omitempty) so callers can rely on\n` + "`" + `exception_message` + "`" + ` existing in every response.",
                    "type": "string",
                    "example": ""
                },
                "exception_status": {
                    "description": "Mirrors the HTTP status the endpoint returned: 200 on success,\n404 when the requested scope resolved to zero catalogs, 500 on\nany downstream failure.",
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "models.GroupCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "rule_group": {
                    "type": "string"
                }
            }
        },
        "models.Rule": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "revert_to_new_criteria": {
                    "description": "RevertToNewCriteria is the RULE_CATALOG.REVERT_TO_NEW_CRITERIA\ncolumn value: the name of a stored procedure that ExecuteRules\ninvokes after the archive/insert/inherit steps to re-evaluate the\ncatalog's non-New rows and flip any that no longer meet the\nexception criteria back to STATUS_ID = 1 ('New'). Empty when the\ncatalog opted out of the revert workflow.",
                    "type": "string"
                },
                "rule_catalog_id": {
                    "type": "integer"
                },
                "rule_catalog_name": {
                    "type": "string"
                },
                "rule_command": {
                    "type": "string"
                }
            }
        },
        "models.RuleForGroup": {
            "type": "object",
            "properties": {
                "catalog_name": {
                    "type": "string"
                },
                "rule_description": {
                    "type": "string"
                },
                "rule_name": {
                    "type": "string"
                }
            }
        },
        "models.RuleGroup": {
            "type": "object",
            "properties": {
                "flag_assign_to_visible": {
                    "type": "boolean"
                },
                "flag_comments_visible": {
                    "type": "boolean"
                },
                "flag_status_visible": {
                    "type": "boolean"
                },
                "flag_suppress_date": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.RuleName": {
            "type": "object",
            "properties": {
                "rule_description": {
                    "type": "string"
                },
                "rule_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/de/securities/rules",
	Schemes:          []string{},
	Title:            "Security Rules API",
	Description:      "REST API for managing security rules, assets, and SECURITY_EXCEPTION rows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
