DROP TABLE IF EXISTS public."DQM_USER";
DROP TABLE IF EXISTS public."DM_USER";

CREATE TABLE public."DM_USER" (
    "ID"    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER"  varchar(100) NOT NULL,
    "ROLE"  varchar(100),
    "EMAIL" varchar(255)
);

INSERT INTO public."DM_USER" ("USER") VALUES
    ('Unassigned'),
    ('Paul Cohen'),
    ('Jake Rigney'),
    ('Anush Safaryan'),
    ('Jimmy Fu'),
    ('Natasha Cabrera'),
    ('Joann Banks'),
    ('Naomi Lynch');

-- Backfill EMAIL + ROLE for the seeded users. Kept as UPDATE-by-name
-- so the statements stay valid even if the surrogate ID sequence has
-- shifted (fresh env vs re-run). "Unassigned" is intentionally left
-- with NULL email + NULL role — it's the placeholder for "no
-- assignee", not a real user.
UPDATE public."DM_USER" SET "EMAIL" = 'Paul.Cohen@tcw.com'      WHERE "USER" = 'Paul Cohen';
UPDATE public."DM_USER" SET "EMAIL" = 'Jake.Rigney@tcw.com'     WHERE "USER" = 'Jake Rigney';
UPDATE public."DM_USER" SET "EMAIL" = 'Anush.Safaryan@tcw.com'  WHERE "USER" = 'Anush Safaryan';
UPDATE public."DM_USER" SET "EMAIL" = 'Jimmy.Fu@tcw.com'        WHERE "USER" = 'Jimmy Fu';
UPDATE public."DM_USER" SET "EMAIL" = 'Natasha.Cabrera@tcw.com' WHERE "USER" = 'Natasha Cabrera';
UPDATE public."DM_USER" SET "EMAIL" = 'Joann.Banks@tcw.com', "ROLE" = 'DM_ADMIN'
 WHERE "USER" = 'Joann Banks';
UPDATE public."DM_USER" SET "EMAIL" = 'Naomi.Lynch@tcw.com', "ROLE" = 'DM_ADMIN'
 WHERE "USER" = 'Naomi Lynch';

-- Every named user other than the DM_ADMINs and Unassigned (the
-- placeholder) gets the default DM_USER role.
UPDATE public."DM_USER" SET "ROLE" = 'DM_USER'
 WHERE "USER" NOT IN ('Joann Banks', 'Naomi Lynch', 'Unassigned');
