DROP TABLE IF EXISTS public."DQM_USER";
DROP TABLE IF EXISTS public."DM_USER";

CREATE TABLE public."DM_USER" (
    "ID"   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "USER" varchar(100) NOT NULL
);

INSERT INTO public."DM_USER" ("USER") VALUES
    ('Unassigned'),
    ('Paul Cohen'),
    ('Jake Rigney'),
    ('Anush Safaryan'),
    ('Jimmy Fu'),
    ('Natasha Cabrera');
