DROP TABLE IF EXISTS public."EXCEPTION_SOURCE_2";

CREATE TABLE public."EXCEPTION_SOURCE_2" (
    "EXCEPTION_SOURCE_ID" integer,
    "NAME"                varchar(100),
    "SORT_ORDER"          integer,
    "CREATED_BY"          varchar(100),
    "CREATED_DATE"        timestamp
);

INSERT INTO public."EXCEPTION_SOURCE_2" (
    "EXCEPTION_SOURCE_ID", "NAME", "SORT_ORDER", "CREATED_BY", "CREATED_DATE"
)
SELECT "EXCEPTION_SOURCE_ID", "CODE", "SORT_ORDER", "MODIFIED_BY", "MODIFIED_DATE"
FROM public."EXCEPTION_SOURCE";
