-- EXCEPTION_OVERRIDE mirrors the EXCEPTION table structure exactly.
-- Kept as a straight DROP+CREATE to match the style of EXCEPTION_pg.sql;
-- live migrations should use ALTER against the deployed instance rather
-- than rerunning this file.

DROP TABLE IF EXISTS public."EXCEPTION_OVERRIDE";

CREATE TABLE public."EXCEPTION_OVERRIDE" (
    "EXCEPTION_ID"        bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000),
    "RULE_ID"             integer,
    "ASSET_ID"            varchar(100),
    "EXCEPTION_DATE"      date,
    "ID_BB_GLOBAL"        varchar(15),
    "STATE_ID"           integer,
    "STATUS_ID"           integer DEFAULT 1,
    "COMMENTS"            varchar(2048),
    "EXCEPTION_TIME"      timestamp,
    "ISSUE_DESCRIPTION"   varchar(512),
    "RESULT_DATA"         json,
    "SUPPRESS_DATE"       date,
    "ASSIGN_TO_ID"        integer,
    "RESULT_TYPE_ID"      integer,
    "CREATED_DATE"        timestamp,
    "CREATED_BY"          varchar(100),
    "MODIFIED_DATE"       timestamp,
    "MODIFIED_BY"         varchar(100)
);
