DROP TABLE IF EXISTS public."EXCEPTION";

CREATE TABLE public."EXCEPTION" (
    "EXCEPTION_ID"        bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000),
    "RULE_ID"             integer,
    "ASSET_ID"            varchar(100),
    "EXCEPTION_DATE"      date,
    "ID_BB_GLOBAL"        varchar(15),
    "STATE_ID"           integer,
    "STATUS_ID"           integer DEFAULT 1,
    "COMMENTS"            varchar(2048),
    "EXCEPTION_TIME"      timestamp,
    "ISSUE_DESCRIPTION"   varchar(512),
    "RESULT_DATA"         json,
    "SUPPRESS_DATE"       date,
    -- Snapshot of the most recent CURRENT_DATE (UTC) on which the row
    -- carried STATUS_ID = 1 ("New"). Written by every INSERT (rows
    -- start New) and by every SP path that flips STATUS_ID back to 1
    -- (SP_UPDATE_EXCEPTION_STATUS, SP_UPDATE_BULK_STATUS,
    -- SP_EXPIRE_SUPPRESS_DATES, SP_INHERIT_EXCEPTION_STATUSES,
    -- SP_UPDATE_EXCEPTION). Transitions to a non-New status
    -- deliberately leave OPEN_DATE untouched.
    "OPEN_DATE"           date,
    -- Companion to OPEN_DATE. Population semantics are declared in a
    -- follow-up (expected: stamped when STATUS_ID moves away from
    -- 'New' → Accept / Override / Suppress / Complete / …; cleared on
    -- transition back to 'New'). Column added first so the schema is
    -- in place before the write-path wiring lands.
    "CLOSE_DATE"          date,
    "ASSIGN_TO_ID"        integer,
    "RESULT_TYPE_ID"      integer,
    "CREATED_DATE"        timestamp,
    "CREATED_BY"          varchar(100),
    "MODIFIED_DATE"       timestamp,
    "MODIFIED_BY"         varchar(100)
);

INSERT INTO public."EXCEPTION" (
    "EXCEPTION_ID", "RULE_ID", "ASSET_ID", "EXCEPTION_DATE", "ID_BB_GLOBAL",
    "STATE_ID", "EXCEPTION_TIME", "ISSUE_DESCRIPTION", "ASSIGN_TO_ID",
    "RESULT_TYPE_ID", "CREATED_DATE", "CREATED_BY"
)
SELECT
    "SECURITY_EXCEPTION_ID"::bigint,
    "RULE_ID"::int,
    "ASSET_ID",
    "RUN_DATE"::date,
    "ID_BB_GLOBAL",
    "EXCEPTION_STATUS_ID"::int,
    "RUN_DATE",
    "ISSUE_DESCRIPTION",
    "ASSIGN_TO_ID"::int,
    "RESULT_TYPE_ID"::int,
    "CREATED_DATE",
    "CREATED_BY"
FROM public."SECURITY_EXCEPTION";
