DROP TABLE IF EXISTS public."EXCEPTION_STATUS";

CREATE TABLE public."EXCEPTION_STATUS" (
    "EXCEPTION_STATUS_ID" integer,
    "NAME"                varchar(100),
    "SORT_ORDER"          integer,
    "CREATED_BY"          varchar(100),
    "CREATED_DATE"        timestamp
);

INSERT INTO public."EXCEPTION_STATUS" (
    "EXCEPTION_STATUS_ID", "NAME", "SORT_ORDER", "CREATED_BY", "CREATED_DATE"
) VALUES
    (1, 'Pending',  10, CURRENT_USER, CURRENT_TIMESTAMP),
    (5, 'OnHold',   15, CURRENT_USER, CURRENT_TIMESTAMP),
    (2, 'Assigned', 20, CURRENT_USER, CURRENT_TIMESTAMP),
    (3, 'WorkedOn', 30, CURRENT_USER, CURRENT_TIMESTAMP),
    (4, 'Complete', 40, CURRENT_USER, CURRENT_TIMESTAMP);
