DROP TABLE IF EXISTS public."EXCEPTION";

CREATE TABLE public."EXCEPTION" (
    "EXCEPTION_ID"        bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000),
    "RULE_ID"             integer,
    "ASSET_ID"            varchar(100),
    "EXCEPTION_DATE"      date,
    "ID_BB_GLOBAL"        varchar(15),
    "STATUS_ID"           integer,
    "COMMENT_ID"          integer,
    "EXCEPTION_TIME"      timestamp,
    "ISSUE_DESCRIPTION"   varchar(512),
    "RESULT_DATA"         json,
    "SUPPRESS_DATE"       date,
    "ASSIGN_TO_ID"        integer,
    "RESULT_TYPE_ID"      integer,
    "CREATED_DATE"        timestamp,
    "CREATED_BY"          varchar(100),
    "MODIFIED_DATE"       timestamp,
    "MODIFIED_BY"         varchar(100)
);

INSERT INTO public."EXCEPTION" (
    "EXCEPTION_ID", "RULE_ID", "ASSET_ID", "EXCEPTION_DATE", "ID_BB_GLOBAL",
    "STATUS_ID", "EXCEPTION_TIME", "ISSUE_DESCRIPTION", "ASSIGN_TO_ID",
    "RESULT_TYPE_ID", "CREATED_DATE", "CREATED_BY"
)
SELECT
    "SECURITY_EXCEPTION_ID"::bigint,
    "RULE_ID"::int,
    "ASSET_ID",
    "RUN_DATE"::date,
    "ID_BB_GLOBAL",
    "EXCEPTION_STATUS_ID"::int,
    "RUN_DATE",
    "ISSUE_DESCRIPTION",
    "ASSIGN_TO_ID"::int,
    "RESULT_TYPE_ID"::int,
    "CREATED_DATE",
    "CREATED_BY"
FROM public."SECURITY_EXCEPTION";
