DROP TABLE IF EXISTS public."EXCEPTION_PROCESS_TYPE";

CREATE TABLE public."EXCEPTION_PROCESS_TYPE" (
    "EXCEPTION_PROCESS_TYPE_ID" integer,
    "NAME"                      varchar(100),
    "SORT_ORDER"                integer,
    "CREATED_BY"                varchar(100),
    "CREATED_DATE"              timestamp
);

INSERT INTO public."EXCEPTION_PROCESS_TYPE" (
    "EXCEPTION_PROCESS_TYPE_ID", "NAME", "SORT_ORDER", "CREATED_BY", "CREATED_DATE"
)
SELECT "PROCESS_TYPE_ID", "CODE", "SORT_ORDER", "MODIFIED_BY", "MODIFIED_DATE"
FROM public."PROCESS_TYPE";
