DROP FUNCTION IF EXISTS public."GET_DM_USERS"();

CREATE OR REPLACE FUNCTION public."GET_DM_USERS"()
RETURNS TABLE("USER" varchar)
LANGUAGE sql
AS $$
    SELECT "USER"
    FROM public."DM_USER"
    ORDER BY "ID" ASC;
$$;
