DROP FUNCTION IF EXISTS public."SP_GET_EXCEPTION_STATE"();

CREATE OR REPLACE FUNCTION public."SP_GET_EXCEPTION_STATE"()
RETURNS TABLE("NAME" text)
LANGUAGE sql
AS $$
    SELECT "NAME"
    FROM public."EXCEPTION_STATE"
    ORDER BY "SORT_ORDER" ASC, "NAME" ASC;
$$;
