DROP FUNCTION IF EXISTS public."GET_EXCEPTION_TYPE"();

CREATE OR REPLACE FUNCTION public."GET_EXCEPTION_TYPE"()
RETURNS TABLE("NAME" text)
LANGUAGE sql
AS $$
    SELECT "NAME"
    FROM public."EXCEPTION_TYPE"
    ORDER BY "SORT_ORDER" ASC, "NAME" ASC;
$$;
