DROP FUNCTION IF EXISTS public."SP_GET_RULE_GROUPS"();

CREATE OR REPLACE FUNCTION public."SP_GET_RULE_GROUPS"()
RETURNS TABLE("NAME" character varying)
LANGUAGE sql
AS $$
    SELECT "NAME"
    FROM public."RULE_GROUP"
    ORDER BY "RULE_GROUP_ID" ASC;
$$;
