DROP FUNCTION IF EXISTS public."SP_GET_SEVERITY_TYPE"();

CREATE OR REPLACE FUNCTION public."SP_GET_SEVERITY_TYPE"()
RETURNS TABLE("NAME" text)
LANGUAGE sql
AS $$
    SELECT "NAME"
    FROM public."EXCEPTION_SEVERITY_TYPE"
    ORDER BY "SORT_ORDER" ASC, "NAME" ASC;
$$;
