DROP FUNCTION IF EXISTS public."GET_EXCEPTION_STATUS"();

CREATE OR REPLACE FUNCTION public."GET_EXCEPTION_STATUS"()
RETURNS TABLE("NAME" text)
LANGUAGE sql
AS $$
    SELECT "NAME"
    FROM public."EXCEPTION_STATUS"
    ORDER BY "SORT_ORDER" ASC, "NAME" ASC;
$$;
