-- Snapshot the current EXCEPTION rows into EXCEPTION_HIST. Explicit column
-- list so the script keeps working if EXCEPTION grows extra columns later.

INSERT INTO public."EXCEPTION_HIST" (
    "EXCEPTION_ID", "RULE_ID", "ASSET_ID", "EXCEPTION_DATE", "ID_BB_GLOBAL",
    "STATE_ID", "COMMENTS", "EXCEPTION_TIME", "ISSUE_DESCRIPTION",
    "RESULT_DATA", "SUPPRESS_DATE", "ASSIGN_TO_ID", "RESULT_TYPE_ID",
    "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY"
)
SELECT
    "EXCEPTION_ID", "RULE_ID", "ASSET_ID", "EXCEPTION_DATE", "ID_BB_GLOBAL",
    "STATE_ID", "COMMENTS", "EXCEPTION_TIME", "ISSUE_DESCRIPTION",
    "RESULT_DATA", "SUPPRESS_DATE", "ASSIGN_TO_ID", "RESULT_TYPE_ID",
    "CREATED_DATE", "CREATED_BY", "MODIFIED_DATE", "MODIFIED_BY"
FROM public."EXCEPTION";
