DROP TABLE IF EXISTS public."RULE_ASSIGN_OVERRIDE";

-- Per-rule assignee override written by the Bulk Assign flow. Latest
-- row per RULE_ID wins in the grid: SP_GET_EXCEPTIONS /
-- SP_GET_EXCEPTIONS_HIST / SP_GET_ASSETS prefer this ASSIGN_TO_ID over
-- RULE.ASSIGN_TO_ID for rows where EXCEPTION.ASSIGN_TO_ID is NULL
-- (per-row grid reassignment still wins over the override).
-- ASSIGN_TO_UNTIL_DATE is recorded but not currently used to expire
-- overrides — metadata for future time-boxed assignments.
CREATE TABLE public."RULE_ASSIGN_OVERRIDE" (
    "RULE_ASSIGN_OVERRIDE_ID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RULE_ID"                 integer NOT NULL,
    "ASSIGN_TO_ID"            integer NOT NULL,
    "ASSIGN_TO_UNTIL_DATE"    date,
    "CREATED_BY"              varchar(100),
    "CREATED_DATE"            timestamp
);
