-- RULE_GROUP schema + seed. Kept as an idempotent script so applying it
-- to an existing DB doesn't wipe data. Adds FLAG_STATUS_VISIBLE,
-- FLAG_COMMENTS_VISIBLE, and FLAG_SUPPRESS_DATE when the columns are
-- missing and seeds them TRUE for 'Security Master'.

CREATE TABLE IF NOT EXISTS public."RULE_GROUP" (
    "RULE_GROUP_ID"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NAME"                  varchar(100),
    "DESCRIPTION"           varchar(512),
    "FLAG_STATUS_VISIBLE"   boolean DEFAULT false,
    "FLAG_COMMENTS_VISIBLE" boolean DEFAULT false,
    "FLAG_SUPPRESS_DATE"    boolean DEFAULT false,
    "CREATED_DATE"          timestamp,
    "CREATED_BY"            varchar(100)
);

ALTER TABLE public."RULE_GROUP"
    ADD COLUMN IF NOT EXISTS "FLAG_STATUS_VISIBLE" boolean DEFAULT false;

ALTER TABLE public."RULE_GROUP"
    ADD COLUMN IF NOT EXISTS "FLAG_COMMENTS_VISIBLE" boolean DEFAULT false;

ALTER TABLE public."RULE_GROUP"
    ADD COLUMN IF NOT EXISTS "FLAG_SUPPRESS_DATE" boolean DEFAULT false;

INSERT INTO public."RULE_GROUP" ("NAME", "DESCRIPTION", "FLAG_STATUS_VISIBLE", "FLAG_COMMENTS_VISIBLE", "FLAG_SUPPRESS_DATE", "CREATED_DATE", "CREATED_BY")
SELECT 'Security Master', 'Security Master', true, true, true, CURRENT_TIMESTAMP, CURRENT_USER
WHERE NOT EXISTS (
    SELECT 1 FROM public."RULE_GROUP" WHERE "NAME" = 'Security Master'
);

UPDATE public."RULE_GROUP"
   SET "FLAG_STATUS_VISIBLE"   = true,
       "FLAG_COMMENTS_VISIBLE" = true,
       "FLAG_SUPPRESS_DATE"    = true
 WHERE "NAME" = 'Security Master';
