DROP TABLE IF EXISTS public."RULE";

CREATE TABLE public."RULE" (
    "RULE_ID"                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RULE_CATALOG_ID"         integer,
    "RULE_NAME"               varchar(100),
    "RULE_DESCRIPTION"        varchar(512),
    "IS_ACTIVE"               numeric(38,0),
    "EXCEPTION_TYPE_ID"       numeric(38,0),
    "EXCEPTION_PROCESS_TYPE_ID"  numeric,
    "EXCEPTION_SEVERITY_TYPE_ID" numeric,
    "EXCEPTION_PRIORITY_TYPE_ID" numeric,
    "EXCEPTION_SOURCE"        numeric,
    "CREATED_BY"              varchar(100),
    "CREATED_DATE"            timestamp
);

INSERT INTO public."RULE" (
    "RULE_CATALOG_ID", "RULE_NAME", "RULE_DESCRIPTION", "IS_ACTIVE",
    "EXCEPTION_TYPE_ID", "EXCEPTION_PROCESS_TYPE_ID", "EXCEPTION_SEVERITY_TYPE_ID",
    "EXCEPTION_PRIORITY_TYPE_ID", "EXCEPTION_SOURCE", "CREATED_BY", "CREATED_DATE"
) VALUES
    (1, 'RULE_DM_BBG_MATURITY_DATE',
        'Compares Maturity Date between Bloomberg and Aladdin',
        1, 1, 1, 1, 2, 1, CURRENT_USER, CURRENT_TIMESTAMP),
    (1, 'RULE_DM_BBG_REGISTRATION',
        'Compares Registration between Bloomberg and Aladdin',
        1, 1, 1, 1, 2, 1, CURRENT_USER, CURRENT_TIMESTAMP);
